import { Request, Response } from 'express';
import prisma from '../lib/prisma.js';
import archiver from 'archiver';

// Helper to generate a clean package.json for the exported project
const generatePackageJson = (projectName: string) => JSON.stringify({
  name: projectName.toLowerCase().replace(/[^a-z0-9-]/g, '-').substring(0, 50) || 'sparkx-website',
  version: '0.1.0',
  private: true,
  scripts: {
    dev: 'vite',
    build: 'vite build',
    preview: 'vite preview',
  },
  dependencies: {
    react: '^18.3.1',
    'react-dom': '^18.3.1',
  },
  devDependencies: {
    '@vitejs/plugin-react': '^4.3.1',
    vite: '^5.4.8',
  },
}, null, 2);

// Helper to generate App.jsx that embeds the full HTML
const generateAppJsx = (htmlCode: string) => {
  // Escape backticks and template literals inside the HTML string
  const escapedHtml = htmlCode.replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
  return `import { useEffect, useRef } from 'react';

const App = () => {
  const iframeRef = useRef(null);

  const htmlCode = \`${escapedHtml}\`;

  return (
    <iframe
      ref={iframeRef}
      srcDoc={htmlCode}
      style={{ width: '100vw', height: '100vh', border: 'none' }}
      title="SparkX Generated Website"
    />
  );
};

export default App;
`;
};

export const exportProject = async (req: Request, res: Response) => {
  try {
    const userId = req.userId;
    const { projectId } = req.params;

    if (!userId) {
      return res.status(401).json({ message: 'Unauthorized' });
    }

    const project = await prisma.websiteProject.findUnique({
      where: { id: projectId, userId },
    });

    if (!project) {
      return res.status(404).json({ message: 'Project not found' });
    }

    if (!project.current_code) {
      return res.status(400).json({ message: 'Project has no generated code yet' });
    }

    const projectName = project.name || 'sparkx-website';

    // Set response headers for ZIP download
    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', `attachment; filename="${projectName.replace(/[^a-zA-Z0-9-]/g, '_')}.zip"`);

    const archive = archiver('zip', { zlib: { level: 9 } });

    archive.on('error', (err) => {
      console.error('Archiver error:', err);
      if (!res.headersSent) {
        res.status(500).json({ message: 'Failed to create ZIP file' });
      }
    });

    // Pipe the archive to the response
    archive.pipe(res);

    // --- File: package.json ---
    archive.append(generatePackageJson(projectName), { name: 'package.json' });

    // --- File: vite.config.js ---
    archive.append(`import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
})
`, { name: 'vite.config.js' });

    // --- File: index.html ---
    archive.append(`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${projectName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
`, { name: 'index.html' });

    // --- File: src/main.jsx ---
    archive.append(`import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App.jsx'

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
`, { name: 'src/main.jsx' });

    // --- File: src/App.jsx ---
    archive.append(generateAppJsx(project.current_code), { name: 'src/App.jsx' });

    // --- File: README.md ---
    archive.append(`# ${projectName}

This project was generated by **SparkX AI Website Builder**.

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

Then open [http://localhost:5173](http://localhost:5173) in your browser.

## Build for Production

\`\`\`bash
npm run build
\`\`\`
`, { name: 'README.md' });

    await archive.finalize();

  } catch (error: any) {
    console.error('exportProject error:', error.message);
    if (!res.headersSent) {
      res.status(500).json({ message: error.message });
    }
  }
};
